---
# title: "research in the press"
toc: true
---
<br>

**When workplace bonuses backfire**<br>
[The Economist](https://www.economist.com/business/2024/10/10/when-workplace-bonuses-backfire)<br>

**Research: When Bonuses Backfire**<br>
[Harvard Business Review Online](https://hbr.org/2024/09/research-when-bonuses-backfire)

**"Mo’ money, mo’ problems?" Bonus incentives are backfiring and making some employees worse at their jobs**<br>
[Fortune](https://fortune.com/2024/09/04/cash-bonus-incentives-backfire-worker-performance-productivity-research-study/)

**Performance Management ist nie problemfrei**<br>
[Personalmagazin](assets\press\Personalmagazin_02_2024_Dirk_Sliwka.pdf)

**Mitarbeitergespräche: Ein typischer Fehler ist, kein differenziertes Feedback einzufordern**<br>
[Wirtschaftswoche](https://www.wiwo.de/erfolg/management/mitarbeitergespraeche-ein-typischer-fehler-ist-kein-differenziertes-feedback-einzufordern/29513670.html)

**40 HR-Köpfe 2023: Big Five**<br>
[Personalmagazin](https://www.haufe.de/personal/personalszene/40-fuehrende-hr-koepfe-preistraeger-2023/40-fuehrende-hr-koepfe-2023-big-five_74_598248.html)

**Interview zu Spot Boni**<br>
[Personalmagazin](assets\press\Interview_SpotBonus_Dirk_Sliwka_Personalmagazin.pdf)

**Trends in der Nutzung von Bonuszahlungen**<br>
[Frankfurter Allgemeine Zeitung](https://www.faz.net/aktuell/karriere-hochschule/buero-co/hohe-bonuszahlungen-koennen-den-wandel-in-firmen-blockieren-17784019.html)

**Personalwissenschaftler aus Niederscheidweiler**<br>
[EifelMosel Zeitung](assets\press\148_Sliwka_Dirk_EifelMoselZeitung_50KW_2021.pdf)

**Wie sich Vergütungsmodelle durch New Work verändern**<br> [Handelsblatt](https://www.handelsblatt.com/karriere/fair-verteilt-wie-sich-verguetungsmodelle-durch-new-work-veraendern/27747632.html)

**Wie halte ich mein Team bei Laune?**<br>
[Frankfurter Allgemeine Zeitung](https://www.faz.net/aktuell/karriere-hochschule/motivation-bei-der-arbeit-wie-halte-ich-mein-team-bei-laune-17574883.html)

**Die 40 führenden HR-Köpfe 2021**<br>
[Personalmagazin](assets\press\KoepfePersonalmagazin2021.pdf)

**Mehr „Wir“, weniger Ziele.**<br>
[Personalmagazin](assets\press\VerguetungsTrendsPersonalmagazin.pdf)

**To Motivate Workers More, Spread Out Pay Raises**<br>
[The Wall Street Journal](http://www.wsj.com/articles/to-motivate-workers-more-spread-out-pay-raises-1456110350)

**Spreading Out Pay Raises Could Make You Work Harder**<br>
[Fortune](https://fortune.com/2016/02/22/wage-raise-study/)

**Great bosses know how to surprise us**<br>
[The Boston Globe](https://www.bostonglobe.com/ideas/2017/06/03/great-bosses-know-how-surprise/2QCUAqaYq7msr877RjZuEM/story.html)

**Economics: Slow and steady**<br>
[Nature Human Behaviour](https://www.nature.com/articles/s41562-017-0090)

**Die Macht der Boni**<br>
[Frankfurter Allgemeine Zeitung](https://www.faz.net/aktuell/karriere-hochschule/buero-co/gehaltssystem-die-macht-der-bonuszahlungen-16465672.html)

**Mitarbeitergespräche: Lästige Pflichtübung oder zielführendes Feedback?**<br>
[Deutschlandfunk](https://www.deutschlandfunk.de/mitarbeitergespraeche-laestige-pflichtuebung-oder-100.html)

**Ein Bonus kann positive Effekte auch zerstören**<br>
[Personalmagazin](https://www.haufe.de/personal/hr-management/interview-d-sliwka-boni-koennen-positive-effekte-zerstoeren_80_501906.html)

**40 Köpfe 2019: Die Wissenschaftler**<br>
[Personalmagazin](https://www.haufe.de/personal/personalszene/die-40-fuehrenden-hr-koepfe/wissenschaftler-und-berater_74_493290.html)

**Evidenzbasiertes Vergütungsdesign**<br>
[Personalwirtschaft](https://www.personalwirtschaft.de/news/verguetung/evidenzbasiertes-verguetungsdesign-148503/)

**Kleine Revolution in der Vergütungspraxis**<br>
[VDI Nachrichten](https://www.vdi-nachrichten.com/karriere/management/kleine-revolution-in-der-verguetungspraxis/)


**Der Mitarbeiter, das Versuchskaninchen?**<br>
[Die Zeit Online](https://www.zeit.de/karriere/beruf/2017-03/personalmanagement-mitarbeiter-fuehrung-experimente)

**Wie viel Gehalt ist noch gerecht?**<br>
[Süddeutsche Zeitung](https://www.sueddeutsche.de/wirtschaft/manager-verguetung-wie-viel-gehalt-ist-noch-gerecht-1.3372945)

**"Werden Mitarbeitergespräche geführt, ist die Arbeitszufriedenheit signifikant höher"**<br>
[Personalmagazin](https://www.haufe.de/personal/hr-management/mitarbeitergespraeche-steigern-arbeitszufriedenheit_80_341052.html)

**Vergütung: Gleiche Position, höheres Gehalt**<br>
[Frankfurter Allgemeine Zeitung](https://www.faz.net/aktuell/karriere-hochschule/recht-und-gehalt/verguetung-gleiche-position-hoeheres-gehalt-1882658.html)