---
#title: "Teaching"
format: html
---

<br>
<br>

**Strategic Human Resource Management**
The key aim of this course in our MSc Business Administration Corporate Development program is to understand how HR management practices can contribute to value creation in an organization and to the execution of its strategy.
<br>
<br>

**People Analytics & Econometrics: The Evaluation of Management Practices**
This course in the MSc Business Administration trains students to analyze personnel data and evaluate management practices working with Python. It covers topics such as survey data and psychological test theory, regressions & statistical Tests, causality and the potential outcome framework, panel data and predictions and machine learning.
<br>
<br>

**The Economics of Incentives in Organizations**
This MSc course is concerned with the economic analysis of incentive contracts combining the analysis of formal economics models with experimental and field evidence.
<br>
<br>

**Corporate Development**
This introductory couse in our Bachelor program covers topics ranging from Corporate Governance, Strategy, Human Resource Management and Organizational Structures.
<br>
<br>

For more details see [Teaching Area Corporate Development](https://cd.wiso.uni-koeln.de/en/study-and-teaching/courses/).
